cleanup craneLib manual imports (#3160)
fixes #3150 

makes accessing filesets and defining new craneLib-dependant derivations
a little easier

---------

Co-authored-by: Nicholas Molnar <65710+neekolas@users.noreply.github.com>

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -49,6 +49,15 @@ jobs:
   validate:
     runs-on: ubuntu-latest
     steps:
+      - name: Validate dev release
+        if: inputs.release-type == 'dev'
+        env:
+          RC_NUMBER: ${{ inputs.rc-number }}
+        run: |
+          if [ -n "$RC_NUMBER" ]; then
+            echo "::error::Dev releases should not have an RC number set"
+            exit 1
+          fi
       - name: Validate release branch
         if: inputs.release-type != 'dev'
         env:
